# General Access
ADMIN_USERNAME={{ arkcase_admin_user }}
ADMIN_PASSWORD={{ arkcase_admin_password }}

# ArkCase Database Parameters
ARKCASE_DB_TYPE={{ db_engine | upper }}
ARKCASE_DB_DIALECT={{ db_engine | upper }}
ARKCASE_DB_HOSTNAME={{ database_host }}
ARKCASE_DB_PORT={{ database_port }}
ARKCASE_DB_DATABASE=arkcase
ARKCASE_DB_USERNAME=arkcase
ARKCASE_DB_PASSWORD={{ encr_password.stdout }}
ARKCASE_DB_JDBC_DRIVER={{ jdbc_driver_class_name }}
ARKCASE_DB_JDBC_URL={{ jdbc_url_properties | replace('SCHEMA', 'arkcase') }}

# ArkCase Access
ARKCASE_URL=https://{{ external_host }}/arkcase
ARKCASE_USERNAME={{ arkcase_admin_user }}@{{ ldap_user_domain }}
ARKCASE_PASSWORD={{ arkcase_admin_encr_password.stdout }}

# Pentaho Access
PENTAHO_URL=https://{{ internal_host }}:2002/pentaho
PENTAHO_USERNAME={{ arkcase_admin_user }}
PENTAHO_PASSWORD={{ arkcase_admin_encr_password.stdout }}


# Specific URLs

ARKCASE_REST_ENDPOINT_LOOKUPS=https://{{ external_host }}/arkcase/api/latest/service/config/lookups
ARKCASE_REST_ENDPOINT_HOLIDAYS=https://{{ external_host }}/arkcase/api/latest/service/holidayConfig
ARKCASE_REST_ENDPOINT_LABELS=https://{{ external_host }}/arkcase/api/latest/plugin/admin/labelmanagement/admin-resource?lang=en&ns=core

