- name: Check if MongoDB root user siteRootAdmin exists
  command: >-
    mongo admin --eval "db.getUser('arkcase')" --ssl --host "{{ internal_host }}"
  register: mongodb_siteRootAdmin

- name: Create MongoDB root user siteRootAdmin
  when: mongodb_siteRootAdmin.stdout.find('userId') == -1
  command: >-
    mongo admin --eval "db.createUser({user: 'arkcase', pwd: '{{ default_user_password }}', roles: [{ role: 'root', db: 'admin' }]})" --ssl --host "{{ internal_host }}"

- name: Check if MongoDB administrative user siteUserAdmin exists
  command: >-
    mongo admin --eval "db.getUser('{{ microservice_mongodb_username }}')" --ssl --host "{{ internal_host }}"
  register: mongodb_siteUserAdmin

- name: Create MongoDB administrative user siteUserAdmin
  when: mongodb_siteUserAdmin.stdout.find('userId') == -1
  command: >-
    mongo admin --eval "db.createUser({user: '{{ microservice_mongodb_username }}', pwd: '{{ microservice_mongodb_password }}', roles: [{ role: 'readWrite', db: '{{ microservice_mongodb_database }}' }, { role: 'readWrite', db: 'admin' }]})"

- name: Check if MongoDB pass_db user exists
  command: >-
    mongo admin --eval "db.getUser('{{ microservice_mongodb_username }}')" --ssl --host "{{ internal_host }}"
  register: mongodb_pass_db

- name: Create pass_db user
  when: mongodb_pass_db.stdout.find('userId') == -1
  command: >-
    mongo admin --eval "db.createUser({user: 'pass_db', pwd: '{{ default_user_password }}', roles: [{ role: 'readWrite', db: 'pass_db' }]})" --ssl --host "{{ internal_host }}"

