# Mongo requires all folders above the log and data 
# folders to have selinux type usr_t
- name: configure parent folders with usr_t selinux type 
  become: yes
  file:
    path: "{{ item }}"
    setype: usr_t
  loop:
    - "{{ root_folder }}/.."
    - "{{ root_folder }}"
    - "{{ root_folder }}/data"
    - "{{ root_folder }}/log"

- name: configure Mongodb 4.0 repository
  become: yes
  copy:
    dest: /etc/yum.repos.d/mongodb-org.repo
    force: true
    content: |
      [mongodb-org-4.0]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.0/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-4.0.asc

- name: ensure mongodb port
  become: true
  command: firewall-cmd --add-port "{{ mongodb_port | default(27017) }}/tcp" --permanent
  register: firewall_ports_updated

- name: See if firewalld is running
  become: true
  ansible.builtin.command: firewall-cmd --state
  register: firewalld_state
  failed_when: false
  changed_when: false

- name: reload the firewall if needed
  become: yes
  command: firewall-cmd --reload
  when: firewall_ports_updated is changed and firewalld_state.stdout == 'running'

- name: install Mongodb
  become: yes
  command: yum -y install mongodb-org
  register: mongodb_install

- name: Mongodb folders
  become: yes
  file:
    path: "{{ item.name }}"
    state: directory
    group: mongod
    owner: mongod
    setype: "{{ item.setype }}"
  loop:
    - name: "{{ root_folder }}/data/mongo"
    #SELinux context on the new dbpath
      setype: "mongod_var_lib_t"
    - name: "{{ root_folder }}/log/mongodb"
    #SELinux context on the new logpath
      setype: "mongod_log_t"
  register: mongodb_folder_structure

- name: create folder to hold MongoDB key
  become: yes
  file:
    path: /etc/mongod
    state: directory
    group: mongod
    owner: mongod

- name: see if MongoD key exists
  become: yes
  stat:
    path: /etc/mongod/mongod.key
  register: mongod_key

- name: create a TLS key per Mongo specs
  become: yes
  shell: cat /etc/pki/tls/certs/{{ internal_host }}.crt /etc/pki/tls/certs/{{ internal_host }}_ca_chain.pem /etc/pki/tls/private/{{ internal_host }}_key.pem | tee /etc/mongod/mongod.key
  when: not mongod_key.stat.exists

- name: set proper ownership on TLS key
  become: yes
  file:
    path: /etc/mongod/mongod.key
    group: mongod
    owner: mongod

- name: Mongodb config
  become: yes
  template:
    src: templates/mongod.conf
    dest: /etc/mongod.conf

- name: enable Mongodb to start on boot
  become: yes
  systemd:
    daemon_reload: true
    name: mongod
    enabled: yes
    masked: no

- name: ensure mongodb is started
  become: yes
  systemd:
    name: mongod
    state: started

- name: install pymongo
  become: yes
  command: "{{ pip_executable }} install --upgrade pymongo"

- name: create arkcase mongo database
  include_tasks: "{{ role_path }}/../mongodb/tasks/create_user_database.yml"
