- name: Import Amazon Corretto GPG key
  become: yes
  ansible.builtin.rpm_key:
    key: https://yum.corretto.aws/corretto.key
    state: present

- name: Install Amazon Corretto 11 from RPM URL
  become: yes
  ansible.builtin.yum:
    name: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.rpm
    state: present

- name: See if the Java truststore exists
  become: yes
  ansible.builtin.stat:
    path: "{{ java_trust_store }}"
  register: arkcase_ts_stat
  changed_when: false

- name: Import server certificates to JDK truststore
  when: arkcase_ts_stat.stat.exists
  block:
    - name: Write Java key store and trust store
      block:
        - name: Add JDK 11 certs to Java trust store
          become: true
          ansible.builtin.command: keytool -importkeystore -srckeystore /usr/lib/jvm/java-11-amazon-corretto/lib/security/cacerts -srcstorepass changeit -destkeystore "{{ java_trust_store }}" -deststorepass {{ java_trust_store_pass }} -noprompt
        - name: Add Arkcase server certs to Java 11 trust store
          become: true
          ansible.builtin.command: keytool -importkeystore -srckeystore "{{ java_trust_store }}" -srcstorepass {{ java_trust_store_pass }} -destkeystore /usr/lib/jvm/java-11-amazon-corretto/lib/security/cacerts -deststorepass changeit -noprompt

#Activemq

- name: set java version
  become: yes
  become_user: activemq
  replace:
    path: "{{ root_folder }}/app/activemq/bin/linux-x86-64/wrapper.conf"
    regexp: "^wrapper.java.command=.*"
    replace: "wrapper.java.command={{ activemq_java_home | default('/usr/lib/jvm/java-11-amazon-corretto') }}/bin/java"


#Arkcase

- name: set Java 11 as Java Home (versions equal and above 2023.02)
  set_fact:
    java_home_version: "/usr/lib/jvm/java-11-amazon-corretto"
  when: arkcase_version == "" or arkcase_version is version('2023.02', '>=')

- include_tasks: "{{ role_path }}/../tomcat/tasks/main.yml"
  args:
    apply:
      vars:
        tc:
          service: arkcase
          user: arkcase
          tomcat_home: "{{ root_folder }}/app/arkcase"
          tls_port: 8843
          shutdown_port: 4005
          jmx_remote_port: 40506
          jmx_rmi_port: 40507
          http_port: 8080
          redirect_port: 4443
          ajp_port: 4009
          catalina_out: "{{ root_folder }}/log/arkcase/catalina.out"
          catalina_temp: "{{ root_folder }}/tmp/arkcase"
          log_folder: "{{ root_folder }}/log/arkcase"
          java_home: "{{java_home_version}}"
  register: tomcat_unarchived

- name: Update JAVA_HOME in config-server.service
  become: yes
  ansible.builtin.replace:
    path: /etc/systemd/system/config-server.service
    regexp: '^Environment=JAVA_HOME=.*$'
    replace: 'Environment=JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto'

- name: Update JAVA_HOME in activemq.service
  become: yes
  ansible.builtin.replace:
    path: /etc/systemd/system/activemq.service
    regexp: '^Environment=JAVA_HOME=.*$'
    replace: 'Environment=JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto'

- name: Reload systemd daemon
  become: yes
  ansible.builtin.command: systemctl daemon-reexec

- name: Restart config-server
  become: yes
  ansible.builtin.service:
    name: config-server
    state: restarted

- name: Restart activemq
  become: yes
  ansible.builtin.service:
    name: activemq
    state: restarted

- name: Remove Java 11 OpenJDK RPM packages
  become: yes
  package:
    name:
      - java-11-openjdk
      - java-11-openjdk-devel
      - java-11-openjdk-headless
    state: absent

- name: Remove residual Java 11 directories
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/java/java-11-openjdk
    - /usr/share/doc/java-11-openjdk-11.0.24.0.8-3.el8.x86_64