###################################################
# Get the analytical reports project and unzip it
###################################################

- name: Set report facts
  ansible.builtin.set_fact:
    foia_analytical_reports_version_formatted: "{{ '-' ~ foia_analytical_reports_version if foia_analytical_reports_version != '' else '' }}"
    doj_reports_repository_id: "arkcase"
    doj_reports_group_id: "com.armedia.arkcase.reports.dw"
    doj_reports_artifact_id: "foia-analytical"
    database_port: "{{ '3306' if 'mariadb' == db_engine else '5432' }}"

- name: set derived report facts
  ansible.builtin.set_fact:
    etl_download_path: "{{ doj_reports_artifact_id }}{{ foia_analytical_reports_version_formatted }}.jar"
    reports_download_path: "{{ doj_reports_artifact_id }}{{ foia_analytical_reports_version_formatted }}-reports.zip"

- name: Create install folder
  become: true
  become_user: pentaho
  ansible.builtin.file:
    path: "{{ root_folder }}/install/pentaho/foia-reports-dw{{ foia_analytical_reports_version_formatted }}"
    mode: '0755'
    state: directory

- name: install python modules needed by maven_artifacts
  become: yes
  command: "{{ ansible_pip3 | default('pip3') }} install lxml"

- name: Download FOIA reports ETL job repository
  become: yes
  become_user: pentaho
  maven_artifact:
    repository_url: "{{ maven_repository_url }}/{{ doj_reports_repository_id }}/"
    group_id: "{{ doj_reports_group_id }}"
    artifact_id: "{{ doj_reports_artifact_id }}"
    version: "{{ foia_analytical_reports_version }}"
    extension: jar
    dest: "{{ root_folder }}/install/pentaho"
    keep_name: true

- name: Download FOIA analytical reports repository
  become: yes
  become_user: pentaho
  maven_artifact:
    repository_url: "{{ maven_repository_url }}/{{ doj_reports_repository_id }}/"
    group_id: "{{ doj_reports_group_id }}"
    artifact_id: "{{ doj_reports_artifact_id }}"
    classifier: "reports"
    version: "{{ foia_analytical_reports_version }}"
    extension: jar
    dest: "{{ root_folder }}/install/pentaho/{{ reports_download_path }}"
    keep_name: true

- name: Unzip ETL repository
  become: true
  become_user: pentaho
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ root_folder }}/install/pentaho/{{ etl_download_path }}"
    dest: "{{ root_folder }}/install/pentaho/foia-reports-dw{{ foia_analytical_reports_version_formatted }}"


# TODO remove this if it's really not needed
#- name: Mondrian schema fixes
#  become: true
#  become_user: pentaho
#  ansible.builtin.replace:
#    backup: true
#    path: "{{ root_folder }}/install/pentaho/foia-reports-dw{{ foia_analytical_reports_version_formatted }}/mondrian_schema/foiaSchema1.4.xml"
#    regexp: 'Cube name="FOIA Cube" visible="true"'
#    replace: 'Cube name="FOIA Cube 1.4" visible="true"'

##########################################################
# Configure the Kettle job files and run the Kettle job.
# This will create and populate the data warehouse tables.
##########################################################

- name: Get the encrypted password for the kettle job
  become: true
  become_user: pentaho-pdi
  ansible.builtin.shell: "set -o pipefail && {{ root_folder }}/app/pentaho-pdi/data-integration/encr.sh -kettle '{{ rds_password | default(default_database_password) }}' | grep Encrypted"
  register: encr_password
  changed_when: false

- name: Get the encrypted password for the cache clean jobs
  become: true
  become_user: pentaho-pdi
  ansible.builtin.shell: "set -o pipefail && {{ root_folder }}/app/pentaho-pdi/data-integration/encr.sh -kettle '{{ arkcase_admin_password }}' | grep Encrypted"
  register: arkcase_admin_encr_password
  changed_when: false

- name: Ensure shared database connection folder exists
  become: true
  become_user: pentaho-pdi
  ansible.builtin.file:
    path: /home/pentaho-pdi/.kettle
    mode: '0755'
    state: directory

- name: Write shared database connection file
  become: true
  become_user: pentaho-pdi
  ansible.builtin.template:
    backup: true
    mode: '0644'
    src: shared.xml
    dest: /home/pentaho-pdi/.kettle/shared.xml

- name: Kettle properties file
  become: true
  become_user: pentaho-pdi
  ansible.builtin.template:
    backup: true
    mode: '0644'
    src: kettle.properties
    dest: /home/pentaho-pdi/.kettle/kettle.properties

- name: Set the cron environment so as to be able to run the job
  become: true
  become_user: pentaho-pdi
  ansible.builtin.cron:
    env: true
    name: "{{ item.name }}"
    job: "{{ item.value }}"
  loop:
    - name: PATH
      value: "/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/pentaho-pdi/.local/bin:/home/pentaho-pdi/bin"
    - name: SHELL
      value: /bin/bash

- name: Schedule the job to run every day at 2 AM
  become: true
  become_user: pentaho-pdi
  ansible.builtin.cron:
    backup: true
    name: "populate FOIA data warehouse tables"
    job: "{{ root_folder }}/app/pentaho-pdi/data-integration/kitchen.sh -file://{{ root_folder }}/install/pentaho/foia-reports-dw{{ foia_analytical_reports_version_formatted }}/foia-dw1.kjb"
    month: "*"
    weekday: "*"
    day: "*"
    hour: "2"
    minute: "0"
    disabled: false
    state: present

###################################################
# Create the JDBC and the Mondrian data sources
###################################################

- name: List the data sources that already exist
  become: true
  become_user: pentaho
  ansible.builtin.command:
    cmd: 'wget --no-check-certificate -O {{ root_folder }}/install/pentaho/datasources-list.json --user={{ arkcase_admin_user }} --password "{{ arkcase_admin_password }}" https://{{ internal_host }}:2002/pentaho/plugin/data-access/api/datasource/jdbc/connection'
  changed_when: false

- name: Read the list of data sources
  become: true
  become_user: pentaho
  ansible.builtin.command: cat {{ root_folder }}/install/pentaho/datasources-list.json
  register: data_source_list
  changed_when: false

- name: File to post to Pentaho to create the data source
  become: true
  become_user: pentaho
  ansible.builtin.template:
    src: put_connection.json
    dest: "{{ root_folder }}/install/pentaho/put_connection.json"
    mode: '0644'
  when: not '"ArkCase"' in data_source_list.stdout

# the ansible uri module causes a timeout for some reason but wget works fine
- name: Create the ArkCase JDBC data source for analytical reports
  ansible.builtin.command:
    cmd: 'wget --no-check-certificate --user={{ arkcase_admin_user }} --password "{{ arkcase_admin_password }}" --post-file {{ root_folder }}/install/pentaho/put_connection.json --header="Content-Type: application/json" https://{{ internal_host }}:2002/pentaho/plugin/data-access/api/connection/add'
  register: create_datasource_rest_call
  when: not '"ArkCase"' in data_source_list.stdout

- name: Upload the Mondrian schema
  become: true
  become_user: pentaho
  ansible.builtin.command:
    cmd: 'curl -k -v -H "Content-Type: multipart/form-data" -X PUT -F uploadInput=@{{ root_folder }}/install/pentaho/foia-reports-dw{{ foia_analytical_reports_version_formatted }}/deploy/foia/{{ foia_mondrian_schema_file }} -F overwrite=true -F xmlaEnabledFlag=false -F parameters="Datasource=ArkCase" -u {{ arkcase_admin_user }}:{{ arkcase_admin_password }} https://{{ internal_host }}:2002/pentaho/plugin/data-access/api/datasource/analysis/catalog/{{ foia_mondrian_schema_file | replace(".xml", "") }}'

#########################################################
# Deploy the reports
#########################################################

- name: Import reports from the zip file archive
  become: true
  become_user: pentaho
  ansible.builtin.command: "{{ root_folder }}/app/pentaho/pentaho-server/import-export.sh --import --url=https://{{ internal_host }}:2002/pentaho --username={{ arkcase_admin_user }} --password='{{ arkcase_admin_password }}' --charset=UTF-8 --path=/public --file-path='{{ root_folder }}/install/pentaho/{{ reports_download_path }}' --permission=true --overwrite=true --retainOwnership=true"

- name: fail early
  fail:
    msg: check if earlier tasks worked

- name: Run the job to create and populate the mondrian cubes
  become: true
  become_user: pentaho-pdi
  ansible.builtin.command:
    cmd: ./kitchen.sh -file://{{ root_folder }}/install/pentaho/foia-reports-dw{{ foia_analytical_reports_version_formatted }}/foia-dw1.kjb
    chdir: "{{ root_folder }}/app/pentaho-pdi/data-integration"